# Generated by Django 4.2.1 on 2023-05-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('precio', models.FloatField()),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
