# Generated by Django 4.2.1 on 2023-05-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
